trigger:
  pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: '$(Configuration)'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.101'

- script: dotnet build
  displayName: 'Build solution'

- script: dotnet test Tests/Unit/*
  displayName: 'Run unit tests'